### ISSUE TITLE
Some errors in code?

### ISSUE THREAD

**Issue by pastaxingxin** [sounakdey/SigNet#3]
Hello!
Recently, I want to re-implement your code by using Hindi dataset.
However, I am a greenhand in deep learning,especially Keras.
When I read your code, I find some trouble puzzling me.
For example. 
example 1, 
![image](https://user-images.githubusercontent.com/17949301/33473393-3ee0ca04-d6b1-11e7-89d9-65f717430364.png)
This 552 should be motified by "size"?

example 2
I want to train my model, what I should do? Should I wipe off  two “#” before "model.fit_generator"?Just like something below?Is this OK?
![image](https://user-images.githubusercontent.com/17949301/33473493-9cfd3f28-d6b1-11e7-86af-8b1b300f1a43.png)

**Comment by pastaxingxin** [comment]
after run the code,I get some error message.Like this
![image](https://user-images.githubusercontent.com/17949301/33473676-50336f90-d6b2-11e7-9336-a3909aeca383.png)

Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`

Should I motify steps_per_epoch and make them same as each other?



what does ETA here mean?

Thank a lot to you in advance.

**Comment by sounakdey** [comment]
For example 1:
Please use the size.... 552 was used later to debug somethings..

For example2:
yes to train your model please uncomment the line model.fit_generator

The messages you get are UserWarnings those are because the code was primarily written in Keras 1 and then adapted at some places for Keras 2 . But i think It will run for Keras 2 with Warnings. If you want to remove it please change the steps_per_epoch to sample_per_epoch but be careful with it because steps_per_epoch is not same as samples_per_epoch because I believe they changed something inside (Please see the documentation).

steps_per_epoch: Total number of steps (batches of samples) to yield from generator before declaring one epoch finished and starting the next epoch. It should typically be equal to the number of unique samples of your dataset divided by the batch size.

ETA means Estimated Time

**Comment by pastaxingxin** [comment]
Many thanks.

After I ran the code to test, I got the following errors:


Traceback (most recent call last):
  File "SigNet_v1.py", line 276, in <module>
    main(args)
  File "SigNet_v1.py", line 246, in main
    model.load_weights(fname)
  File "/home/lijingdi/anaconda_ete/lib/python2.7/site-packages/keras/engine/topology.py", line 2616, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/lijingdi/anaconda_ete/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/lijingdi/anaconda_ete/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/lijingdi/panxingxin/writeridentification/copy2/SigNet-master/SigNet-master/SigNet/weights_Hindi.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) 


1.what does result in this error message? What  I should do to solve it?

**Comment by pastaxingxin** [comment]
As for the output.There are some things puzzling me.

![image](https://user-images.githubusercontent.com/17949301/33532895-73fd3802-d8d8-11e7-9a5c-c7427a13382d.png)

You can see the loss start to be "nan".
what does this mean?
It means that accuracy of prediction is 100% ?or it means that there is some bugs?

**Comment by pastaxingxin** [comment]
?please

**Comment by sounakdey** [comment]
For h5py error... Its explained by the error itself 'No such file or directory'....Please give the right path...
Please check this issue I hope it helps you with the loss: Nan .....

**Comment by sounakdey** [comment]
https://github.com/sounakdey/SigNet/issues/1 this one

**Comment by pastaxingxin** [comment]
Thank you very much.
yes, “Nan” problem is solved.
However,for h5py error, I still cannot solve that.
I have "pip install h5py " and import it.Also my path is correct.
But it seems doesn't save model sucessfully.

**Comment by sounakdey** [comment]
I dont think you have this weights_Hindi.hdf5 file please comment the line and train it from the beginning...

**Comment by pastaxingxin** [comment]
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 16 12:24:27 2017
@author: sounak_dey and anjan_dutta
"""
import numpy as np
np.random.seed(1337)  # for reproducibility
import os
import argparse
import h5py
#from keras.utils.visualize_util import plot
import tensorflow as tf
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras.layers import Dense, Dropout, Input, Lambda, Flatten, Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.preprocessing import image
from keras import backend as K
from SignatureDataGenerator import SignatureDataGenerator
import getpass as gp
import sys
from keras.models import Sequential, Model
from keras.optimizers import SGD, RMSprop, Adadelta
from keras.layers.normalization import BatchNormalization
from keras.regularizers import l2
import random
random.seed(1337)
# Create a session for running Ops on the Graph.
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
K.set_session(sess)
def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True))
def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)
def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    return K.mean(y_true * K.square(y_pred) + (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))
def create_base_network_signet(input_shape):
    seq = Sequential()
    seq.add(Convolution2D(96, 11, 11, activation='relu', name='conv1_1', subsample=(4, 4), input_shape= input_shape, 
                        init='glorot_uniform', dim_ordering='tf'))
    seq.add(BatchNormalization(epsilon=1e-06, mode=0, axis=1, momentum=0.9))
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))    
    seq.add(ZeroPadding2D((2, 2), dim_ordering='tf'))
    seq.add(Convolution2D(256, 5, 5, activation='relu', name='conv2_1', subsample=(1, 1), init='glorot_uniform',  dim_ordering='tf'))
    seq.add(BatchNormalization(epsilon=1e-06, mode=0, axis=1, momentum=0.9))
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))
    seq.add(Dropout(0.3))# added extra
    seq.add(ZeroPadding2D((1, 1), dim_ordering='tf'))
    seq.add(Convolution2D(384, 3, 3, activation='relu', name='conv3_1', subsample=(1, 1), init='glorot_uniform',  dim_ordering='tf'))
    seq.add(ZeroPadding2D((1, 1), dim_ordering='tf'))
    seq.add(Convolution2D(256, 3, 3, activation='relu', name='conv3_2', subsample=(1, 1), init='glorot_uniform', dim_ordering='tf'))    
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))
    seq.add(Dropout(0.3))# added extra
    seq.add(Flatten(name='flatten'))
    seq.add(Dense(1024, W_regularizer=l2(0.0005), activation='relu', init='glorot_uniform'))
    seq.add(Dropout(0.5))
    seq.add(Dense(128, W_regularizer=l2(0.0005), activation='relu', init='glorot_uniform')) # softmax changed to relu
    return seq

def compute_accuracy_roc(predictions, labels):
   '''Compute ROC accuracy with a range of thresholds on distances.
   '''
   dmax = np.max(predictions)
   dmin = np.min(predictions)
   nsame = np.sum(labels == 1)
   ndiff = np.sum(labels == 0)
   step = 0.01
   max_acc = 0
   for d in np.arange(dmin, dmax+step, step):
       idx1 = predictions.ravel() <= d
       idx2 = predictions.ravel() > d
       tpr = float(np.sum(labels[idx1] == 1)) / nsame       
       tnr = float(np.sum(labels[idx2] == 0)) / ndiff
       acc = 0.5 * (tpr + tnr)       
       print ('ROC', acc, tpr, tnr)
       if (acc > max_acc):
           max_acc = acc
   return max_acc
    
def read_signature_data(dataset, ntuples, height = 30, width = 100):
    usr = gp.getuser()
    image_dir = '/home/lijingdi/panxingxin/writeridentification/copy2/BHSig260/' + dataset + '/' 
    data_file = image_dir +  'sum.txt'
    f = open( data_file, 'r' )
    lines = f.readlines()
    f.close()
    idx = np.random.choice(list(range(len(lines))), ntuples)
    lines = [lines[i] for i in idx]
    images = []
    for line in lines:
        file1, file2, label = line.split(' ')
        img1 = image.load_img(image_dir + file1, grayscale = True, 
                target_size=(height, width))
        img1 = image.img_to_array(img1)#, dim_ordering='tf')
        images.append(img1)
        img2 = image.load_img(image_dir + file1, grayscale = True, 
                target_size=(height, width))
        img2 = image.img_to_array(img2)#, dim_ordering='tf')
        images.append(img2)
    return np.array(images)
        
def main(args):
    dataset = args.dataset
    if dataset == 'Bengali':
        tot_writers = 100
        num_train_writers = 80
        num_valid_writers = 10
    elif dataset == 'Hindi':
        tot_writers = 160
        num_train_writers = 100
        num_valid_writers = 10
    elif dataset == 'GPDS300':
        tot_writers = 300
        num_train_writers = 240
        num_valid_writers = 30
    elif dataset == 'GPDS960':
        tot_writers = 4000
        num_train_writers = 3200
        num_valid_writers = 400
    elif dataset == 'CEDAR1':
        tot_writers = 55
        num_train_writers = 45
        num_valid_writers = 5
    
    num_test_writers = tot_writers - (num_train_writers + num_valid_writers)
    batch_sz = args.batch_size #128
    nsamples = args.num_samples #276 
    img_height = 155
    img_width = 220
    featurewise_center = False
    featurewise_std_normalization = True
    zca_whitening = False
    nb_epoch = args.epoch #20    
    input_shape=(img_height, img_width, 1) 
    datagen = SignatureDataGenerator(dataset, tot_writers, num_train_writers, 
        num_valid_writers, num_test_writers, nsamples, batch_sz, img_height, img_width,
        featurewise_center, featurewise_std_normalization, zca_whitening)
    X_sample = read_signature_data(dataset, int(0.5*tot_writers), height=img_height, width=img_width)
    datagen.fit(X_sample)
    del X_sample
    base_network = create_base_network_signet(input_shape)
    input_a = Input(shape=(input_shape))
    input_b = Input(shape=(input_shape))
    processed_a = base_network(input_a)
    processed_b = base_network(input_b)
    distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])  
    model = Model(input=[input_a, input_b], output=distance)
    rms = RMSprop(lr=1e-4, rho=0.9, epsilon=1e-08)
    adadelta = Adadelta()
    model.compile(loss=contrastive_loss, optimizer=rms)
    fname = os.path.join('/home/' , 'weights_'+str(dataset)+'.hdf5')
    checkpointer = ModelCheckpoint(filepath=fname, verbose=1, save_best_only=True)
    model.fit_generator(generator=datagen.next_train(), steps_per_epoch=datagen.samples_per_train, epochs=nb_epoch,
                         validation_data=datagen.next_valid(), validation_steps=120, callbacks=[checkpointer])  # KERAS 2
    model.load_weights(fname)
    print (fname)
    print ('Loading the best weights for testing done...') 
    te_pred = model.predict_generator(generator=datagen.next_test(), steps=120)
    te_acc = compute_accuracy_roc(te_pred, datagen.test_labels)
    print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))
 
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Signature Verification')

    parser.add_argument('--dataset', '-ds', action='store', type=str, required=True,
                  help='Please mention the database.')

    parser.add_argument('--epoch', '-e', action='store', type=int, default=2, 
                  help='The maximum number of iterations. Default: 20')
    parser.add_argument('--num_samples', '-ns', action='store', type=int, default=20, 
                  help='The number of samples. Default: 276')
    parser.add_argument('--batch_size', '-bs', action='store', type=int, default=16,
                  help='The mini batch size. Default: 138')
    args = parser.parse_args()

    main(args)

**Comment by pastaxingxin** [comment]
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 16 12:24:27 2017
@author: sounak_dey and anjan_dutta
"""
import numpy as np
np.random.seed(1337)  # for reproducibility
import os
import argparse
import h5py
#from keras.utils.visualize_util import plot
import tensorflow as tf
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras.layers import Dense, Dropout, Input, Lambda, Flatten, Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.preprocessing import image
from keras import backend as K
from SignatureDataGenerator import SignatureDataGenerator
import getpass as gp
import sys
from keras.models import Sequential, Model
from keras.optimizers import SGD, RMSprop, Adadelta
from keras.layers.normalization import BatchNormalization
from keras.regularizers import l2
import random
random.seed(1337)
# Create a session for running Ops on the Graph.
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
K.set_session(sess)
def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True))
def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)
def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    return K.mean(y_true * K.square(y_pred) + (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))
def create_base_network_signet(input_shape):
    seq = Sequential()
    seq.add(Convolution2D(96, 11, 11, activation='relu', name='conv1_1', subsample=(4, 4), input_shape= input_shape, 
                        init='glorot_uniform', dim_ordering='tf'))
    seq.add(BatchNormalization(epsilon=1e-06, mode=0, axis=1, momentum=0.9))
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))    
    seq.add(ZeroPadding2D((2, 2), dim_ordering='tf'))
    seq.add(Convolution2D(256, 5, 5, activation='relu', name='conv2_1', subsample=(1, 1), init='glorot_uniform',  dim_ordering='tf'))
    seq.add(BatchNormalization(epsilon=1e-06, mode=0, axis=1, momentum=0.9))
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))
    seq.add(Dropout(0.3))# added extra
    seq.add(ZeroPadding2D((1, 1), dim_ordering='tf'))
    seq.add(Convolution2D(384, 3, 3, activation='relu', name='conv3_1', subsample=(1, 1), init='glorot_uniform',  dim_ordering='tf'))
    seq.add(ZeroPadding2D((1, 1), dim_ordering='tf'))
    seq.add(Convolution2D(256, 3, 3, activation='relu', name='conv3_2', subsample=(1, 1), init='glorot_uniform', dim_ordering='tf'))    
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))
    seq.add(Dropout(0.3))# added extra
    seq.add(Flatten(name='flatten'))
    seq.add(Dense(1024, W_regularizer=l2(0.0005), activation='relu', init='glorot_uniform'))
    seq.add(Dropout(0.5))
    seq.add(Dense(128, W_regularizer=l2(0.0005), activation='relu', init='glorot_uniform')) # softmax changed to relu
    return seq

def compute_accuracy_roc(predictions, labels):
   '''Compute ROC accuracy with a range of thresholds on distances.
   '''
   dmax = np.max(predictions)
   dmin = np.min(predictions)
   nsame = np.sum(labels == 1)
   ndiff = np.sum(labels == 0)
   step = 0.01
   max_acc = 0
   for d in np.arange(dmin, dmax+step, step):
       idx1 = predictions.ravel() <= d
       idx2 = predictions.ravel() > d
       tpr = float(np.sum(labels[idx1] == 1)) / nsame       
       tnr = float(np.sum(labels[idx2] == 0)) / ndiff
       acc = 0.5 * (tpr + tnr)       
       print ('ROC', acc, tpr, tnr)
       if (acc > max_acc):
           max_acc = acc
   return max_acc
    
def read_signature_data(dataset, ntuples, height = 30, width = 100):
    usr = gp.getuser()
    image_dir = '/home/lijingdi/panxingxin/writeridentification/copy2/BHSig260/' + dataset + '/' 
    data_file = image_dir +  'sum.txt'
    f = open( data_file, 'r' )
    lines = f.readlines()
    f.close()
    idx = np.random.choice(list(range(len(lines))), ntuples)
    lines = [lines[i] for i in idx]
    images = []
    for line in lines:
        file1, file2, label = line.split(' ')
        img1 = image.load_img(image_dir + file1, grayscale = True, 
                target_size=(height, width))
        img1 = image.img_to_array(img1)#, dim_ordering='tf')
        images.append(img1)
        img2 = image.load_img(image_dir + file1, grayscale = True, 
                target_size=(height, width))
        img2 = image.img_to_array(img2)#, dim_ordering='tf')
        images.append(img2)
    return np.array(images)
        
def main(args):
    dataset = args.dataset
    if dataset == 'Bengali':
        tot_writers = 100
        num_train_writers = 80
        num_valid_writers = 10
    elif dataset == 'Hindi':
        tot_writers = 160
        num_train_writers = 100
        num_valid_writers = 10
    elif dataset == 'GPDS300':
        tot_writers = 300
        num_train_writers = 240
        num_valid_writers = 30
    elif dataset == 'GPDS960':
        tot_writers = 4000
        num_train_writers = 3200
        num_valid_writers = 400
    elif dataset == 'CEDAR1':
        tot_writers = 55
        num_train_writers = 45
        num_valid_writers = 5
    
    num_test_writers = tot_writers - (num_train_writers + num_valid_writers)
    batch_sz = args.batch_size #128
    nsamples = args.num_samples #276 
    img_height = 155
    img_width = 220
    featurewise_center = False
    featurewise_std_normalization = True
    zca_whitening = False
    nb_epoch = args.epoch #20    
    input_shape=(img_height, img_width, 1) 
    datagen = SignatureDataGenerator(dataset, tot_writers, num_train_writers, 
        num_valid_writers, num_test_writers, nsamples, batch_sz, img_height, img_width,
        featurewise_center, featurewise_std_normalization, zca_whitening)
    X_sample = read_signature_data(dataset, int(0.5*tot_writers), height=img_height, width=img_width)
    datagen.fit(X_sample)
    del X_sample
    base_network = create_base_network_signet(input_shape)
    input_a = Input(shape=(input_shape))
    input_b = Input(shape=(input_shape))
    processed_a = base_network(input_a)
    processed_b = base_network(input_b)
    distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])  
    model = Model(input=[input_a, input_b], output=distance)
    rms = RMSprop(lr=1e-4, rho=0.9, epsilon=1e-08)
    adadelta = Adadelta()
    model.compile(loss=contrastive_loss, optimizer=rms)
    fname = os.path.join('/home/' , 'weights_'+str(dataset)+'.hdf5')
    checkpointer = ModelCheckpoint(filepath=fname, verbose=1, save_best_only=True)
    model.fit_generator(generator=datagen.next_train(), steps_per_epoch=datagen.samples_per_train, epochs=nb_epoch,
                         validation_data=datagen.next_valid(), validation_steps=120, callbacks=[checkpointer])  # KERAS 2
    model.load_weights(fname)
    print (fname)
    print ('Loading the best weights for testing done...') 
    te_pred = model.predict_generator(generator=datagen.next_test(), steps=120)
    te_acc = compute_accuracy_roc(te_pred, datagen.test_labels)
    print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))
 
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Signature Verification')

    parser.add_argument('--dataset', '-ds', action='store', type=str, required=True,
                  help='Please mention the database.')

    parser.add_argument('--epoch', '-e', action='store', type=int, default=2, 
                  help='The maximum number of iterations. Default: 20')
    parser.add_argument('--num_samples', '-ns', action='store', type=int, default=20, 
                  help='The number of samples. Default: 276')
    parser.add_argument('--batch_size', '-bs', action='store', type=int, default=16,
                  help='The mini batch size. Default: 138')
    args = parser.parse_args()

    main(args)

**Comment by pastaxingxin** [comment]
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 16 12:24:27 2017
@author: sounak_dey and anjan_dutta
"""
import numpy as np
np.random.seed(1337)  # for reproducibility
import os
import argparse
import h5py
#from keras.utils.visualize_util import plot
import tensorflow as tf
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras.layers import Dense, Dropout, Input, Lambda, Flatten, Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.preprocessing import image
from keras import backend as K
from SignatureDataGenerator import SignatureDataGenerator
import getpass as gp
import sys
from keras.models import Sequential, Model
from keras.optimizers import SGD, RMSprop, Adadelta
from keras.layers.normalization import BatchNormalization
from keras.regularizers import l2
import random
random.seed(1337)
# Create a session for running Ops on the Graph.
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
K.set_session(sess)
def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True))
def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)
def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    return K.mean(y_true * K.square(y_pred) + (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))
def create_base_network_signet(input_shape):
    seq = Sequential()
    seq.add(Convolution2D(96, 11, 11, activation='relu', name='conv1_1', subsample=(4, 4), input_shape= input_shape, 
                        init='glorot_uniform', dim_ordering='tf'))
    seq.add(BatchNormalization(epsilon=1e-06, mode=0, axis=1, momentum=0.9))
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))    
    seq.add(ZeroPadding2D((2, 2), dim_ordering='tf'))
    seq.add(Convolution2D(256, 5, 5, activation='relu', name='conv2_1', subsample=(1, 1), init='glorot_uniform',  dim_ordering='tf'))
    seq.add(BatchNormalization(epsilon=1e-06, mode=0, axis=1, momentum=0.9))
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))
    seq.add(Dropout(0.3))# added extra
    seq.add(ZeroPadding2D((1, 1), dim_ordering='tf'))
    seq.add(Convolution2D(384, 3, 3, activation='relu', name='conv3_1', subsample=(1, 1), init='glorot_uniform',  dim_ordering='tf'))
    seq.add(ZeroPadding2D((1, 1), dim_ordering='tf'))
    seq.add(Convolution2D(256, 3, 3, activation='relu', name='conv3_2', subsample=(1, 1), init='glorot_uniform', dim_ordering='tf'))    
    seq.add(MaxPooling2D((3,3), strides=(2, 2)))
    seq.add(Dropout(0.3))# added extra
    seq.add(Flatten(name='flatten'))
    seq.add(Dense(1024, W_regularizer=l2(0.0005), activation='relu', init='glorot_uniform'))
    seq.add(Dropout(0.5))
    seq.add(Dense(128, W_regularizer=l2(0.0005), activation='relu', init='glorot_uniform')) # softmax changed to relu
    return seq

def compute_accuracy_roc(predictions, labels):
   '''Compute ROC accuracy with a range of thresholds on distances.
   '''
   dmax = np.max(predictions)
   dmin = np.min(predictions)
   nsame = np.sum(labels == 1)
   ndiff = np.sum(labels == 0)
   step = 0.01
   max_acc = 0
   for d in np.arange(dmin, dmax+step, step):
       idx1 = predictions.ravel() <= d
       idx2 = predictions.ravel() > d
       tpr = float(np.sum(labels[idx1] == 1)) / nsame       
       tnr = float(np.sum(labels[idx2] == 0)) / ndiff
       acc = 0.5 * (tpr + tnr)       
       print ('ROC', acc, tpr, tnr)
       if (acc > max_acc):
           max_acc = acc
   return max_acc
    
def read_signature_data(dataset, ntuples, height = 30, width = 100):
    usr = gp.getuser()
    image_dir = '/home/lijingdi/panxingxin/writeridentification/copy2/BHSig260/' + dataset + '/' 
    data_file = image_dir +  'sum.txt'
    f = open( data_file, 'r' )
    lines = f.readlines()
    f.close()
    idx = np.random.choice(list(range(len(lines))), ntuples)
    lines = [lines[i] for i in idx]
    images = []
    for line in lines:
        file1, file2, label = line.split(' ')
        img1 = image.load_img(image_dir + file1, grayscale = True, 
                target_size=(height, width))
        img1 = image.img_to_array(img1)#, dim_ordering='tf')
        images.append(img1)
        img2 = image.load_img(image_dir + file1, grayscale = True, 
                target_size=(height, width))
        img2 = image.img_to_array(img2)#, dim_ordering='tf')
        images.append(img2)
    return np.array(images)
        
def main(args):
    dataset = args.dataset
    if dataset == 'Bengali':
        tot_writers = 100
        num_train_writers = 80
        num_valid_writers = 10
    elif dataset == 'Hindi':
        tot_writers = 160
        num_train_writers = 100
        num_valid_writers = 10
    elif dataset == 'GPDS300':
        tot_writers = 300
        num_train_writers = 240
        num_valid_writers = 30
    elif dataset == 'GPDS960':
        tot_writers = 4000
        num_train_writers = 3200
        num_valid_writers = 400
    elif dataset == 'CEDAR1':
        tot_writers = 55
        num_train_writers = 45
        num_valid_writers = 5
    
    num_test_writers = tot_writers - (num_train_writers + num_valid_writers)
    batch_sz = args.batch_size #128
    nsamples = args.num_samples #276 
    img_height = 155
    img_width = 220
    featurewise_center = False
    featurewise_std_normalization = True
    zca_whitening = False
    nb_epoch = args.epoch #20    
    input_shape=(img_height, img_width, 1) 
    datagen = SignatureDataGenerator(dataset, tot_writers, num_train_writers, 
        num_valid_writers, num_test_writers, nsamples, batch_sz, img_height, img_width,
        featurewise_center, featurewise_std_normalization, zca_whitening)
    X_sample = read_signature_data(dataset, int(0.5*tot_writers), height=img_height, width=img_width)
    datagen.fit(X_sample)
    del X_sample
    base_network = create_base_network_signet(input_shape)
    input_a = Input(shape=(input_shape))
    input_b = Input(shape=(input_shape))
    processed_a = base_network(input_a)
    processed_b = base_network(input_b)
    distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])  
    model = Model(input=[input_a, input_b], output=distance)
    rms = RMSprop(lr=1e-4, rho=0.9, epsilon=1e-08)
    adadelta = Adadelta()
    model.compile(loss=contrastive_loss, optimizer=rms)
    fname = os.path.join('/home/' , 'weights_'+str(dataset)+'.hdf5')
    checkpointer = ModelCheckpoint(filepath=fname, verbose=1, save_best_only=True)
    model.fit_generator(generator=datagen.next_train(), steps_per_epoch=datagen.samples_per_train, epochs=nb_epoch,
                         validation_data=datagen.next_valid(), validation_steps=120, callbacks=[checkpointer])  # KERAS 2
    model.load_weights(fname)
    print (fname)
    print ('Loading the best weights for testing done...') 
    te_pred = model.predict_generator(generator=datagen.next_test(), steps=120)
    te_acc = compute_accuracy_roc(te_pred, datagen.test_labels)
    print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))
 
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Signature Verification')

    parser.add_argument('--dataset', '-ds', action='store', type=str, required=True,
                  help='Please mention the database.')

    parser.add_argument('--epoch', '-e', action='store', type=int, default=2, 
                  help='The maximum number of iterations. Default: 20')
    parser.add_argument('--num_samples', '-ns', action='store', type=int, default=20, 
                  help='The number of samples. Default: 276')
    parser.add_argument('--batch_size', '-bs', action='store', type=int, default=16,
                  help='The mini batch size. Default: 138')
    args = parser.parse_args()

    main(args)

**Comment by pastaxingxin** [comment]
def main(args):
    dataset = args.dataset
    if dataset == 'Bengali':
        tot_writers = 100
        num_train_writers = 80
        num_valid_writers = 10
    elif dataset == 'Hindi':
        tot_writers = 160
        num_train_writers = 100
        num_valid_writers = 10
    elif dataset == 'GPDS300':
        tot_writers = 300
        num_train_writers = 240
        num_valid_writers = 30
    elif dataset == 'GPDS960':
        tot_writers = 4000
        num_train_writers = 3200
        num_valid_writers = 400
    elif dataset == 'CEDAR1':
        tot_writers = 55
        num_train_writers = 45
        num_valid_writers = 5
    
    num_test_writers = tot_writers - (num_train_writers + num_valid_writers)
    batch_sz = args.batch_size #128
    nsamples = args.num_samples #276 
    img_height = 155
    img_width = 220
    featurewise_center = False
    featurewise_std_normalization = True
    zca_whitening = False
    nb_epoch = args.epoch #20    
    input_shape=(img_height, img_width, 1) 
    datagen = SignatureDataGenerator(dataset, tot_writers, num_train_writers, 
        num_valid_writers, num_test_writers, nsamples, batch_sz, img_height, img_width,
        featurewise_center, featurewise_std_normalization, zca_whitening)
    X_sample = read_signature_data(dataset, int(0.5*tot_writers), height=img_height, width=img_width)
    datagen.fit(X_sample)
    del X_sample
    base_network = create_base_network_signet(input_shape)
    input_a = Input(shape=(input_shape))
    input_b = Input(shape=(input_shape))
    processed_a = base_network(input_a)
    processed_b = base_network(input_b)
    distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])  
    model = Model(input=[input_a, input_b], output=distance)
    rms = RMSprop(lr=1e-4, rho=0.9, epsilon=1e-08)
    adadelta = Adadelta()
    model.compile(loss=contrastive_loss, optimizer=rms)
    fname = os.path.join('/home/' , 'weights_'+str(dataset)+'.hdf5')
    checkpointer = ModelCheckpoint(filepath=fname, verbose=1, save_best_only=True)
    model.fit_generator(generator=datagen.next_train(), steps_per_epoch=datagen.samples_per_train, epochs=nb_epoch,
                         validation_data=datagen.next_valid(), validation_steps=120, callbacks=[checkpointer])  # KERAS 2
    model.load_weights(fname)
    print (fname)
    print ('Loading the best weights for testing done...') 
    te_pred = model.predict_generator(generator=datagen.next_test(), steps=120)
    te_acc = compute_accuracy_roc(te_pred, datagen.test_labels)
    print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))
 
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Signature Verification')

    parser.add_argument('--dataset', '-ds', action='store', type=str, required=True,
                  help='Please mention the database.')

    parser.add_argument('--epoch', '-e', action='store', type=int, default=2, 
                  help='The maximum number of iterations. Default: 20')
    parser.add_argument('--num_samples', '-ns', action='store', type=int, default=20, 
                  help='The number of samples. Default: 276')
    parser.add_argument('--batch_size', '-bs', action='store', type=int, default=16,
                  help='The mini batch size. Default: 138')
    args = parser.parse_args()

    main(args)

**Comment by pastaxingxin** [comment]
There is main code.
I still cannnot seek a solution.I don't know why it cannot save model.
Could you please see them?
![image](https://user-images.githubusercontent.com/17949301/33651215-fda4fd1a-da9f-11e7-9188-092524adbc51.png)

**Comment by sounakdey** [comment]
Can you please open a new issue and I will post the answer on to it...
