### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0?

### ISSUE THREAD

**Issue by pastaxingxin** [sounakdey/SigNet#4]
Hello, I ran the SigNet_v1.py by using "--dataset GPDS300 --epoch 1 --num_samples 18 --batch_size 16" for test.
Some errors happen.
For tail -10 of stdout：
![image](https://user-images.githubusercontent.com/17949301/34080979-731e6542-e381-11e7-8130-ad2464a2b72f.png)

For stderr:
![image](https://user-images.githubusercontent.com/17949301/34080962-28d46978-e381-11e7-9f38-b4dde7450daf.png)

there seems a error. Could you please tell me how to modify the codes?
Thanks for you in advance

**Comment by pastaxingxin** [comment]
hello, could you tell me how to resolve the error?

**Comment by pastaxingxin** [comment]
hello, could you tell me how to resolve the error?

**Comment by sounakdey** [comment]
Sorry I was in a holiday.. It seems the ground truth label size does not match with that of the number of test images

**Comment by pastaxingxin** [comment]
So, how to modify your false code?

**Comment by sounakdey** [comment]
It is a problem with your dataset not the code... It is verified ... Please be polite with your level of expertise
